/** Phase 3 strings: doctors, specialties and appointment booking. */
export const p3 = {
  en: {
    // doctors / specialties
    doctorManagement: "Doctor Management",
    specialtyManagement: "Specialties",
    addDoctor: "Add Doctor",
    editDoctor: "Edit Doctor",
    doctorName: "Doctor Name",
    specialty: "Specialty",
    qualification: "Qualification",
    availableDays: "Available Days",
    days: "Days",
    opdTiming: "Actual OPD Timing",
    opdTimingHint: "e.g. 5:00 PM – 7:00 PM",
    fee: "Appointment Fee",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    activate: "Activate",
    deactivate: "Deactivate",
    save: "Save",
    saved: "Saved successfully",
    addSpecialty: "Add Specialty",
    specialtyName: "Specialty Name (English)",
    specialtyNameUr: "Specialty Name (Urdu)",
    duplicateSpecialty: "This specialty already exists",
    noDoctors: "No doctors found",
    selectDoctor: "Select Doctor",
    searchDoctorPlaceholder: "Search by doctor name",
    allSpecialties: "All specialties",
    anyDay: "Any day",
    // booking
    bookAppointment: "Book Appointment",
    stepPatient: "Patient",
    stepDoctor: "Doctor",
    stepDate: "Date",
    stepReview: "Review",
    choosePatient: "Who is this appointment for?",
    useExistingPatient: "Choose an existing patient",
    newPatient: "New patient details",
    appointmentDate: "Appointment Date",
    pickDate: "Select an available future date",
    noAvailableDays: "This doctor has no working days configured.",
    reviewAppointment: "Review Appointment",
    confirmAppointment: "Confirm Appointment",
    booking: "Booking…",
    appointmentConfirmed: "Appointment Confirmed",
    appointmentNumber: "Appointment Number",
    backToDashboard: "Back to Dashboard",
    next: "Next",
    // my appointments
    myAppointments: "My Appointments",
    upcoming: "Upcoming",
    previous: "Previous",
    noAppointments: "No appointments yet",
    appointmentStatus: "Appointment Status",
    statusSearchNote: "Search with your Appointment Number or Mobile Number.",
    statusCreated: "Appointment Created",
    statusConfirmed: "Confirmed",
    statusCancelled: "Cancelled",
    statusCompleted: "Completed",
    // admin
    adminAppointments: "Appointments",
    filterDate: "Date",
    filterStatus: "Status",
    allStatuses: "All statuses",
    searchAppointments: "Search by number, name, mobile, MR, doctor",
    bookingAccount: "Booking Google Account",
    details: "Details",
    noPermission: "You do not have permission for this action.",
    manageDoctors: "Manage Doctors",
    weekdays: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    weekdaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    doctorInactiveError: "This doctor is not available for new appointments.",
    invalidDate: "Please select an available future date.",
  },
  ur: {
    doctorManagement: "ڈاکٹر مینجمنٹ",
    specialtyManagement: "شعبہ جات",
    addDoctor: "ڈاکٹر شامل کریں",
    editDoctor: "ڈاکٹر میں ترمیم",
    doctorName: "ڈاکٹر کا نام",
    specialty: "شعبہ",
    qualification: "قابلیت",
    availableDays: "دستیاب دن",
    days: "دن",
    opdTiming: "او پی ڈی کا اصل وقت",
    opdTimingHint: "مثلاً 5:00 PM – 7:00 PM",
    fee: "اپائنٹمنٹ فیس",
    status: "حیثیت",
    active: "فعال",
    inactive: "غیر فعال",
    activate: "فعال کریں",
    deactivate: "غیر فعال کریں",
    save: "محفوظ کریں",
    saved: "کامیابی سے محفوظ ہو گیا",
    addSpecialty: "شعبہ شامل کریں",
    specialtyName: "شعبے کا نام (انگریزی)",
    specialtyNameUr: "شعبے کا نام (اردو)",
    duplicateSpecialty: "یہ شعبہ پہلے سے موجود ہے",
    noDoctors: "کوئی ڈاکٹر نہیں ملا",
    selectDoctor: "ڈاکٹر منتخب کریں",
    searchDoctorPlaceholder: "ڈاکٹر کے نام سے تلاش کریں",
    allSpecialties: "تمام شعبے",
    anyDay: "کوئی بھی دن",
    bookAppointment: "اپائنٹمنٹ بک کریں",
    stepPatient: "مریض",
    stepDoctor: "ڈاکٹر",
    stepDate: "تاریخ",
    stepReview: "نظرثانی",
    choosePatient: "یہ اپائنٹمنٹ کس کے لیے ہے؟",
    useExistingPatient: "موجودہ مریض منتخب کریں",
    newPatient: "نئے مریض کی تفصیلات",
    appointmentDate: "اپائنٹمنٹ کی تاریخ",
    pickDate: "دستیاب آئندہ تاریخ منتخب کریں",
    noAvailableDays: "اس ڈاکٹر کے کام کے دن مقرر نہیں ہیں۔",
    reviewAppointment: "اپائنٹمنٹ پر نظرثانی",
    confirmAppointment: "اپائنٹمنٹ کی تصدیق کریں",
    booking: "بک ہو رہی ہے…",
    appointmentConfirmed: "اپائنٹمنٹ کی تصدیق ہو گئی",
    appointmentNumber: "اپائنٹمنٹ نمبر",
    backToDashboard: "ڈیش بورڈ پر واپس",
    next: "آگے",
    myAppointments: "میری اپائنٹمنٹس",
    upcoming: "آئندہ",
    previous: "گزشتہ",
    noAppointments: "ابھی کوئی اپائنٹمنٹ نہیں",
    appointmentStatus: "اپائنٹمنٹ کی صورتحال",
    statusSearchNote: "اپنا اپائنٹمنٹ نمبر یا موبائل نمبر درج کریں۔",
    statusCreated: "اپائنٹمنٹ بن گئی",
    statusConfirmed: "تصدیق شدہ",
    statusCancelled: "منسوخ",
    statusCompleted: "مکمل",
    adminAppointments: "اپائنٹمنٹس",
    filterDate: "تاریخ",
    filterStatus: "حیثیت",
    allStatuses: "تمام حیثیتیں",
    searchAppointments: "نمبر، نام، موبائل، ایم آر یا ڈاکٹر سے تلاش کریں",
    bookingAccount: "بکنگ گوگل اکاؤنٹ",
    details: "تفصیلات",
    noPermission: "آپ کے پاس اس کام کی اجازت نہیں ہے۔",
    manageDoctors: "ڈاکٹرز کا انتظام",
    weekdays: ["اتوار", "پیر", "منگل", "بدھ", "جمعرات", "جمعہ", "ہفتہ"],
    weekdaysShort: ["اتوار", "پیر", "منگل", "بدھ", "جمعرات", "جمعہ", "ہفتہ"],
    doctorInactiveError: "یہ ڈاکٹر نئی اپائنٹمنٹ کے لیے دستیاب نہیں۔",
    invalidDate: "براہ کرم دستیاب آئندہ تاریخ منتخب کریں۔",
  },
};
