/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as MasterAdminRouteImport } from './routes/master-admin'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as RoleRouteImport } from './routes/role'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFindRecordRouteImport } from './routes/_authenticated/find-record'
import { Route as AuthenticatedPatientRecordsRouteImport } from './routes/_authenticated/patient-records'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRegisterRouteImport } from './routes/_authenticated/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterAdminRoute = MasterAdminRouteImport.update({
  id: '/master-admin',
  path: '/master-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindRecordRoute = AuthenticatedFindRecordRouteImport.update({
  id: '/find-record',
  path: '/find-record',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientRecordsRoute =
  AuthenticatedPatientRecordsRouteImport.update({
    id: '/patient-records',
    path: '/patient-records',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegisterRoute = AuthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/language': typeof LanguageRoute
  '/master-admin': typeof MasterAdminRoute
  '/patient': typeof PatientRoute
  '/role': typeof RoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/find-record': typeof AuthenticatedFindRecordRoute
  '/patient-records': typeof AuthenticatedPatientRecordsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/register': typeof AuthenticatedRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/language': typeof LanguageRoute
  '/master-admin': typeof MasterAdminRoute
  '/patient': typeof PatientRoute
  '/role': typeof RoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/find-record': typeof AuthenticatedFindRecordRoute
  '/patient-records': typeof AuthenticatedPatientRecordsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/register': typeof AuthenticatedRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/language': typeof LanguageRoute
  '/master-admin': typeof MasterAdminRoute
  '/patient': typeof PatientRoute
  '/role': typeof RoleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/find-record': typeof AuthenticatedFindRecordRoute
  '/_authenticated/patient-records': typeof AuthenticatedPatientRecordsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/register': typeof AuthenticatedRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/language'
    | '/master-admin'
    | '/patient'
    | '/role'
    | '/dashboard'
    | '/find-record'
    | '/patient-records'
    | '/profile'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/language'
    | '/master-admin'
    | '/patient'
    | '/role'
    | '/dashboard'
    | '/find-record'
    | '/patient-records'
    | '/profile'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/language'
    | '/master-admin'
    | '/patient'
    | '/role'
    | '/_authenticated/dashboard'
    | '/_authenticated/find-record'
    | '/_authenticated/patient-records'
    | '/_authenticated/profile'
    | '/_authenticated/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  LanguageRoute: typeof LanguageRoute
  MasterAdminRoute: typeof MasterAdminRoute
  PatientRoute: typeof PatientRoute
  RoleRoute: typeof RoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-admin': {
      id: '/master-admin'
      path: '/master-admin'
      fullPath: '/master-admin'
      preLoaderRoute: typeof MasterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/find-record': {
      id: '/_authenticated/find-record'
      path: '/find-record'
      fullPath: '/find-record'
      preLoaderRoute: typeof AuthenticatedFindRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient-records': {
      id: '/_authenticated/patient-records'
      path: '/patient-records'
      fullPath: '/patient-records'
      preLoaderRoute: typeof AuthenticatedPatientRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/register': {
      id: '/_authenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFindRecordRoute: typeof AuthenticatedFindRecordRoute
  AuthenticatedPatientRecordsRoute: typeof AuthenticatedPatientRecordsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRegisterRoute: typeof AuthenticatedRegisterRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFindRecordRoute: AuthenticatedFindRecordRoute,
  AuthenticatedPatientRecordsRoute: AuthenticatedPatientRecordsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRegisterRoute: AuthenticatedRegisterRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  LanguageRoute: LanguageRoute,
  MasterAdminRoute: MasterAdminRoute,
  PatientRoute: PatientRoute,
  RoleRoute: RoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
